using System;
using System.Windows.Forms;
using System.Data.SqlClient;
using System.Data;
using System.Data.OleDb;

namespace Lab_And_Tutor_Finder_System
{
    /// <summary>
    /// Project: Forage
    /// Programmer: Emandleni Moyo s216673380@mandela.ac.za
    /// Date: 2019/07/11
    /// Description: This class defines the behavior of the student registration form.
    /// </summary>
    public partial class StudentRegistrationForm : Form
    {

        //OleDbConnection connection = new OleDbConnection(@"Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\Admin\Documents\WRR301.mdf;Integrated Security=True;Connect Timeout=30;Encrypt=False;TrustServerCertificate=True;ApplicationIntent=ReadWrite;MultiSubnetFailover=False");
        OleDbConnection connection = new OleDbConnection();
        public StudentRegistrationForm()
        {
            InitializeComponent();
            connection.ConnectionString = @"Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\Wande\Documents\WRR\Forage.accdb;
            Persist Security Info=False;";
        }

        private void Form2_Load(object sender, EventArgs e)
        {

        }

        /**
         * Registers user onto system.
         * If the user does not have an existing account, creates a new account and shows them the student dashboard.
         **/
        private void registerButton_Click(object sender, EventArgs e)
        {
            if (connection.State == ConnectionState.Closed)
                connection.Open();
    
            if (!isExisting(userNameTextBox.Text, connection))
            {
                OleDbCommand command = new OleDbCommand(@"INSERT INTO Student VALUES ('" + userNameTextBox.Text + "', '" + passwordTextBox.Text + "', '" + firstNameTextBox.Text + "', '" + lastNameTextBox.Text + "')",connection);
                command.ExecuteNonQuery();

                connection.Close();
                MessageBox.Show("Successfully registered "+firstNameTextBox.Text+"!", "Complete", MessageBoxButtons.OK, MessageBoxIcon.Information);
                this.Hide();
                new StudentEntryForm().Show();
            }
            else //If the user has an existing account 
            {
                MessageBox.Show("We already know you here "+firstNameTextBox.Text+"! Rather log in.", "Account already exists", MessageBoxButtons.OK, MessageBoxIcon.Information);
            }

        }

        /**
         *  Verifies that the student user does not have an existing account on the system
         **/
        private bool isExisting(string str1, OleDbConnection connection)
        {
            string selectQuery = "SELECT * FROM Student WHERE studentUsername = '" + str1 + "'";
            //Gets hold of the result set generated by the SQL query
            OleDbDataAdapter dataAdapter = new OleDbDataAdapter(selectQuery, connection);
            DataTable dataTable = new DataTable();
            dataAdapter.Fill(dataTable);

            //Iterates through the result set, if there is a row matching
            if (dataTable.Rows.Count > 0)
                return true;
            else return false;
        }

        /**
         *  Redirects user to log in window
         **/
        private void CancelButton_Click(object sender, EventArgs e)
        {
            this.Hide();
            new LoginForm().Show();
        }
    }
}
